// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxU0ILFGJnh4NGwLtMG9jaEdc8CyLF6Mo',
    appId: '1:247734268457:web:6d89a56ef30e9d5765a238',
    messagingSenderId: '247734268457',
    projectId: 'notetakingapp-14840',
    authDomain: 'notetakingapp-14840.firebaseapp.com',
    storageBucket: 'notetakingapp-14840.firebasestorage.app',
    measurementId: 'G-XCF42JBB2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkPQbF8__ZSHynAgXGHo7E_r0gyDIOHY',
    appId: '1:247734268457:android:8d863b8002ac7b3f65a238',
    messagingSenderId: '247734268457',
    projectId: 'notetakingapp-14840',
    storageBucket: 'notetakingapp-14840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzWFwf62jdjUxKPTozaaqN7QCH0GSZMk',
    appId: '1:247734268457:ios:59d87daeb8be9bf565a238',
    messagingSenderId: '247734268457',
    projectId: 'notetakingapp-14840',
    storageBucket: 'notetakingapp-14840.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtzWFwf62jdjUxKPTozaaqN7QCH0GSZMk',
    appId: '1:247734268457:ios:59d87daeb8be9bf565a238',
    messagingSenderId: '247734268457',
    projectId: 'notetakingapp-14840',
    storageBucket: 'notetakingapp-14840.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxU0ILFGJnh4NGwLtMG9jaEdc8CyLF6Mo',
    appId: '1:247734268457:web:26c357289437801f65a238',
    messagingSenderId: '247734268457',
    projectId: 'notetakingapp-14840',
    authDomain: 'notetakingapp-14840.firebaseapp.com',
    storageBucket: 'notetakingapp-14840.firebasestorage.app',
    measurementId: 'G-PKN7DPPJQ5',
  );
}
